POST http://localhost:3000/api/register
Content-Type: application/json

{
    "lastname": "Doe",
    "pseudo": "dfghj",
    "email": "t@t.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "123456"
}

###
GET http://localhost:3000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MTQ3MjcwMTUsImV4cCI6MTcxNDgxMzQxNX0.syMsKaZcU-U93kcdXI3d65pIdWA4Aa_BTbwbM-wdijM

### GET articles without token
GET http://localhost:3000/api/articles

### GET articles with token
GET http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MTQ3MjcwMTUsImV4cCI6MTcxNDgxMzQxNX0.syMsKaZcU-U93kcdXI3d65pIdWA4Aa_BTbwbM-wdijM

### POST article with token
POST http://localhost:3000/api/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MTc1NzM1NzUsImV4cCI6MTcxNzY1OTk3NX0.5H-3qcWXffo6NFak3lUZOwHn74Z3gLkpHSiF5YZLunE

{
    "title": "Article 1",
    "content": "Content 1"
}
### PUT article with token
PUT http://localhost:3000/api/articles/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MTc1NzM1NzUsImV4cCI6MTcxNzY1OTk3NX0.5H-3qcWXffo6NFak3lUZOwHn74Z3gLkpHSiF5YZLunE

{
    "status": "DRAFT"
}

### DELETE article with token
DELETE http://localhost:3000/api/articles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MTQ3MjcwMTUsImV4cCI6MTcxNDgxMzQxNX0.syMsKaZcU-U93kcdXI3d65pIdWA4Aa_BTbwbM-wdijM